# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d1c3c571f3e032e3d6a233750a02429f58a8fac2ea6481f738f6f128f78e66c76177972c3c971b9e719dbacc80f6cc625c1befba7f7dc9aada38510a8b6750

test:
  secret_key_base: 7d4f331039356a78d94cef2644faf57b86cc1b1d2d88d55c5af94fe64db2b13f0bf236817ebe133d7b5959846585e096c74e7487ca781a7bf1310316b8bca90a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
